team-truman-show/pokedex-server

.gitignore, models/connection.js, models/index.js, package-lock.json, package.json
초기 세팅
<br><br>
초기 세팅
<br><br>
<br><br>
- Close #1 
<br><br>
=> add: 초기 세팅

.gitignore, app.js, models/connection.js, models/index.js, models/mypoketmons.js, models/poketmons.js, models/users.js, package-lock.json, package.json
<br><br>
db모델 생성(poketmons, users, mypoketmons), db연결
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> add: db모델 생성및 db 연결

app.js, models/index.js, models/mypoketmons.js, models/poketmons.js, models/users.js, package.json, rotuer/user.js
fix: 깃 실수 fix
<br><br>
fix: 깃 실수 fix
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> fix: 깃 실수 fix

app.js, lib/passwordUtil.js, models/connection.js, models/index.js, package.json, service/signup.js
회원가입 기능
<br><br>
회원가입로직과 암호화 추가
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> add:회원가입기능 추가

app.js, lib/tokenUtil.js, lib/verifyUtil.js, models/users.js, service/login.js, service/signup.js
비밀번호검증코드 추가
<br><br>
verifyUtil 추가
if (!req.body.userid || !req.body.password || !req.body.nickname) {
return res.status(400).send("모든 값을 입력해주세요");
} 회원가입 코드에서 값을 전부 안집어넣엇을때 오류 출력하게끔 코드 추가
로그인 코드에서 비밀번호 검증 추가
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> 비밀번호검증코드 추가

lib/verifyUtil.js, models/index.js, models/mypokemons.js, models/pokemons.js, models/users.js, rotuer/user.js
db 이름 변경
<br><br>
poketmon 에서 pokemon으로 변경
<br><br>
<br><br>
- Close #12 
<br><br>
=> update: db 이름 변경

rotuer/user.js, service/update.js
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> fix:닉네임변경함수 분리

app.js, lib/tokenUtil.js, models/pokemons.js, rotuer/pokemon.js, rotuer/user.js, service/login.js, service/pokeapi.js, service/signup.js
포켓몬 db에 저장
<br><br>
포켓몬 db에 저장했습니다.
<br><br>
<br><br>
- Close #21 
<br><br>
=> add: 포켓몬 db에 저장

rotuer/pokemon.js, rotuer/user.js
오류 처리 수정
<br><br>
에러 처리 수정
<br><br>
<br><br>
- Close #26 
<br><br>
=> update: 안바뀐 부분 수정

rotuer/pokemon.js, service/pokeapi.js
이름으로 포켓몬 검색
<br><br>
이름으로 검색
<br><br>
<br><br>
- Close #29 
<br><br>
=> add: 이름으로 포켓몬 찾기

app.js, lib/passwordUtil.js, rotuer/user.js, service/find.js, service/login.js, service/signup.js, service/update.js
<br>비밀번호 찾기 기능 추가
userid와 nickname이 일치한다면 password변경및 암호화<br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> 비밀번호찾기(변경)기능 추가

lib/passwordUtil.js, rotuer/user.js, service/find.js, service/update.js
<br>비밀번호 변경및 암호화 함수 추가<br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> Feature #28 add : 비밀번호 변경 추가

app.js, rotuer/pokemon.js, rotuer/user.js, service/pokesearch.js, service/pwchange.js
<br>포켓몬 이름으로 찾기기능 추가<br>
<br>포켓몬 이름으로 찾기기능 추가<br>
<br><br>
- Close #이슈번호
<br><br>
=> add:포켓몬 이름으로 찾기기능 추가

models/mypokemons.js, models/pokemons.js, rotuer/pokemon.js, service/pokeapi.js
add: 포켓몬 db에서 id로 검색
<br><br>
포켓몬 db에서 id로 검색
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> add: 포켓몬 db에서 id로 검색

README.md, rotuer/pokemon.js, service/searchAll.js
<br>포켓몬전체조회추가<br>
<br>포켓몬전체조회<br>
<br><br>
- Close #이슈번호
<br><br>
=> Feature #40 add:포켓몬 전체조회 추가

rotuer/user.js
<br>토큰을 json형태로<br>
<br>login 부분의 send부분을 json형태로 변경<br>
<br><br>
- Close #이슈번호
<br><br>
=> fix:토큰json형태

app.js, lib/loginUtil.js, lib/tokenUtil.js, models/mypokemons.js, models/users.js, package-lock.json, package.json, rotuer/pokemon.js, rotuer/user.js, service/catch.js, service/join.js, service/login.js, service/pwchange.js, service/update.js
add: 잡기 기능 추가
<br><br>
add: 잡기 기능 추가
<br><br>
<br><br>
- Close #39
<br><br>
=> add: 잡기 기능 추가

app.js, rotuer/pokemon.js, service/pokeapi.js
fix: get post 수정
<br><br>
fix: get post 수정
<br><br>
<br><br>
- Close #46 
<br><br>
=> fix: get post 수정

lib/tokenUtil.js, rotuer/pokemon.js, rotuer/user.js, service/catch.js, service/idsearch.js, service/myinformation.js, service/mypokemon.js
my page 기능 추가
<br><br>
my page 백엔드 기능 추가
<br><br>
<br><br>
- Close #46 
<br><br>
=> add:my page 기능 추가

lib/loginUtil.js, rotuer/pokemon.js, rotuer/user.js, service/searchAll.js
add:프론트와 연동하며 기능 수정
<br><br>
add:프론트와 연동하며 기능 수정
<br><br>
<br><br>
- Close #49 
<br><br>
=> add:프론트와 연동하며 기능 수정

app.js, package-lock.json, package.json, service/searchAll.js
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> fix:전체적인 코드 확인

lib/tokenUtil.js, service/catch.js
전체 기능 체크
<br><br>
기능 체크
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> fix: 전체 기능 체크

.gitignore, rotuer/pokemon.js
확률 위치 조정
<br><br>
fix:확률 위치 조정
<br><br>
<br><br>
- Close #57 
<br><br>
=> fix:확률 위치 조정

app.js, rotuer/pokemon.js, rotuer/user.js, service/infoUpdate.js, service/pokeCatch.js, service/pokesearch.js
1차 발표
<br><br>
1차발표
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> add: 1차 발표

models/mypokemons.js
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> add: 내 포켓몬 테이블에 컬럼 추가

API/evolve.js, API/pokeapi copy.js, app.js, models/evolves.js, package-lock.json, package.json
<br>DB 테이블 생성 및 API를 이용한 데이터 처리<br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> add: DB 및 API 수정

service/mypokemonService/pokeCatch.js
<br>포켓몬 상태<br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> Feature #70 add: 상태

API/evolve.js, lib/loginUtil.js, router/mypokemon.js, router/pokeBringUp.js, router/pokemon.js, service/gameService/evolve.js, service/gameService/pokeBringUp.js
<br>일부 구현<br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> add: 진화 API 기능 구현 중

API/pokeapi.js, API/pokesave.js, app.js, router/mypokemon.js, router/pokemon.js, service/gameService/pokeBringUp.js
fix:연동 버그 수정
<br><br>
fix:연동 버그 수정
<br><br>
<br><br>
- Close #81 
<br><br>
=> fix:연동 버그 수정

lib/tokenUtil.js, router/mypokemon.js, service/mypokemonService/findPokemon.js
fix:중복 포켓몬
<br><br>
fix:중복 포켓몬
<br><br>
<br><br>
- Close #83 
<br><br>
=> fix:중복 포켓몬
